// GENERATED by scripts/stamp-version.js — do not edit by hand.
// The whole monorepo shares one version; see the root package.json.
const String appVersion = '0.1.15';
const int appBuildNumber = 15;
