#!/usr/bin/env node
/**
 * Stamps the version release-it just picked into everything that isn't the
 * root package.json.
 *
 * release-it bumps the root manifest and knows nothing about the rest, but
 * this repo ships one version across four formats: the two npm workspaces,
 * the Flutter pubspec, and a generated Dart constant. Run from the
 * "after:bump" hook in .release-it.json, before the release commit is made.
 *
 *   node scripts/stamp-version.js 1.4.0
 */
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

const PACKAGE_FILES = ["apps/backend/package.json", "apps/frontend/package.json"];
const PUBSPEC = "apps/mobile-app/pubspec.yaml";
const DART_VERSION_FILE = "apps/mobile-app/lib/version.dart";

/** Rewrites only the version line, so formatting and key order survive. */
function writeVersion(relative, version) {
  const file = path.join(ROOT, relative);
  const before = fs.readFileSync(file, "utf8");
  const after = before.replace(/"version":\s*"[^"]*"/, `"version": "${version}"`);
  if (before === after) throw new Error(`No version field to update in ${relative}`);
  fs.writeFileSync(file, after);
}

/**
 * Android refuses an update whose versionCode isn't higher than the
 * installed one, and it has to be an integer — so the build number after
 * the "+" counts releases and only ever goes up.
 */
function nextBuildNumber(pubspec) {
  const match = pubspec.match(/^version:\s*\S+?(?:\+(\d+))?\s*$/m);
  if (!match) throw new Error(`No version line found in ${PUBSPEC}`);
  return Number(match[1] ?? 0) + 1;
}

function main() {
  const version = process.argv[2];
  if (!version || !/^\d+\.\d+\.\d+/.test(version)) {
    console.error(`Usage: node scripts/stamp-version.js <version>  (got "${version ?? ""}")`);
    process.exit(1);
  }

  for (const file of PACKAGE_FILES) writeVersion(file, version);

  const pubspecPath = path.join(ROOT, PUBSPEC);
  const pubspec = fs.readFileSync(pubspecPath, "utf8");
  const build = nextBuildNumber(pubspec);
  fs.writeFileSync(pubspecPath, pubspec.replace(/^version:\s*.*$/m, `version: ${version}+${build}`));

  // Dart can't read pubspec.yaml at runtime without pulling in a package
  // for it, so the version is generated into a source file instead.
  fs.writeFileSync(
    path.join(ROOT, DART_VERSION_FILE),
    "// GENERATED by scripts/stamp-version.js — do not edit by hand.\n" +
      "// The whole monorepo shares one version; see the root package.json.\n" +
      `const String appVersion = '${version}';\n` +
      `const int appBuildNumber = ${build};\n`
  );

  // The lockfile records each workspace's version, so leaving it behind
  // makes `npm ci` refuse to install on the server. --package-lock-only
  // rewrites it without touching node_modules.
  // --ignore-scripts because the root postinstall runs `flutter pub get`,
  // which has nothing to do with rewriting a lockfile.
  execFileSync("npm", ["install", "--package-lock-only", "--ignore-scripts", "--silent"], {
    cwd: ROOT,
    stdio: "inherit",
    shell: process.platform === "win32",
  });

  // Staged explicitly so the release commit carries them whatever
  // release-it's own staging is configured to do.
  execFileSync(
    "git",
    ["add", ...PACKAGE_FILES, PUBSPEC, DART_VERSION_FILE, "package-lock.json"],
    { cwd: ROOT, stdio: "inherit" }
  );

  console.log(`Stamped ${version} (Android build ${build}) across the workspaces and the Flutter app.`);
}

main();
